### ISSUE TITLE
double-clicking on etensor cell in tableview causes crash

### ISSUE THREAD

**Issue by rcoreilly** [emer/etable#36]
```go
oreilly@shadow:~/ccnsims/ch3/cats_dogs/ > ./cats_dogs
NThreads: 1	go max procs: 16	num cpu:16
panic: interface conversion: ki.Ki is nil, not *gi.Layout

goroutine 28 [running]:
github.com/emer/etable/etview.(*TensorView).GridLayout(0xc0004ac300, 0x400f445)
	/Users/oreilly/go/src/github.com/emer/etable/etview/tensorview.go:122 +0xd5
github.com/emer/etable/etview.(*TensorView).SliceGrid(0xc0004ac300, 0x543ec48)
	/Users/oreilly/go/src/github.com/emer/etable/etview/tensorview.go:128 +0x2f
github.com/emer/etable/etview.(*TensorView).ConfigSliceGrid(0xc0004ac300)
	/Users/oreilly/go/src/github.com/emer/etable/etview/tensorview.go:164 +0x11e
github.com/emer/etable/etview.(*TensorView).Config(0xc0004ac300)
	/Users/oreilly/go/src/github.com/emer/etable/etview/tensorview.go:101 +0x285
github.com/emer/etable/etview.(*TensorView).SetTensor(0xc0004ac300, 0x542b680, 0xc005376c80, 0x0, 0x0)
	/Users/oreilly/go/src/github.com/emer/etable/etview/tensorview.go:70 +0x1be
github.com/emer/etable/etview.TensorViewDialog(0xc005433500, 0x542b680, 0xc005376c80, 0x5195a56, 0xb, 0x53d6138, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/oreilly/go/src/github.com/emer/etable/etview/dialogs.go:39 +0x2f4
github.com/emer/etable/etview.(*TensorGrid).OpenTensorView(0xc000493900)
	/Users/oreilly/go/src/github.com/emer/etable/etview/tensorgrid.go:203 +0xb5
github.com/emer/etable/etview.(*TensorGrid).MouseEvent.func1(0x543e420, 0xc000493900, 0x5444b70, 0xc005453000, 0x0, 0x50a00e0, 0xc007905740)
	/Users/oreilly/go/src/github.com/emer/etable/etview/tensorgrid.go:226 +0xb5
github.com/goki/gi/gi.(*WinEventRecv).Call(0xc000653dc0, 0x5444b70, 0xc005453000, 0x0, 0x50a00e0, 0xc007905740)
	/Users/oreilly/go/src/github.com/goki/gi/gi/events.go:116 +0x8c
github.com/goki/gi/gi.(*EventMgr).SendEventSignal(0xc005453188, 0x5412470, 0xc007905740, 0x1)
	/Users/oreilly/go/src/github.com/goki/gi/gi/events.go:225 +0x3ae
github.com/goki/gi/gi.(*Window).ProcessEvent(0xc005453000, 0x5412470, 0xc007905740)
	/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:1576 +0x925
github.com/goki/gi/gi.(*Window).EventLoop(0xc005453000)
	/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:1498 +0x36
created by github.com/goki/gi/gi.(*Window).GoStartEventLoop
	/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:877 +0xa7
```

**Comment by rcoreilly** [comment]
kind of a big bug -- affects all usage of TensorView -- now fixed.
