### ISSUE TITLE
eplot crash

### ISSUE THREAD

**Issue by rcoreilly** [emer/etable#46]
cd /Users/oreilly/go/src/github.com/emer/axon/examples/ra25 (from: {FileDirPath})
NThreads: 1	go max procs: 10	num cpu:10
panic: runtime error: index out of range [1] with length 1

goroutine 6 [running]:
github.com/emer/etable/etensor.(*Int64).FloatVal1D(0x101b1da00?, 0x140001b5516?)
	/Users/oreilly/go/src/github.com/emer/etable/etensor/numeric.gen.go:135 +0x4c
github.com/emer/etable/eplot.(*Plot2D).PlotXAxis(0x140006e0300, 0x1400b76e000, 0x14000d096e0)
	/Users/oreilly/go/src/github.com/emer/etable/eplot/eplot2d.go:365 +0x460
github.com/emer/etable/eplot.(*Plot2D).GenPlotXY(0x140006e0300)
	/Users/oreilly/go/src/github.com/emer/etable/eplot/xyplot.go:45 +0x41c
github.com/emer/etable/eplot.(*Plot2D).GenPlot(0x140006e0300)
	/Users/oreilly/go/src/github.com/emer/etable/eplot/eplot2d.go:295 +0xb4
github.com/emer/etable/eplot.(*Plot2D).Layout2D(0x140006e0300, {{0x140006e0300?, 0x12d55e618?}, {0x1400036c000?, 0x1400a6bb1d8?}}, 0x100da867c?)
	/Users/oreilly/go/src/github.com/emer/etable/eplot/eplot2d.go:729 +0x5c
github.com/goki/gi/gi.(*Layout).Layout2DChildren(0x14000ad8100, 0x1?)
	/Users/oreilly/go/src/github.com/goki/gi/gi/layout.go:520 +0x13c
github.com/goki/gi/gi.(*Layout).Layout2D(0x14000ad8100, {{0x14000ad8100?, 0x12f51e348?}, {0x14000ada000?, 0x1400a6bb2e8?}}, 0x0)
	/Users/oreilly/go/src/github.com/goki/gi/gi/layout.go:1205 +0x1a0
github.com/goki/gi/gi.(*Layout).Layout2DChildren(0x1400036c000, 0x0?)
	/Users/oreilly/go/src/github.com/goki/gi/gi/layout.go:525 +0x1a4
github.com/goki/gi/gi.(*Layout).Layout2D(0x1400036c000, {{0x1400036c000?, 0x101a707e0?}, {0x0?, 0x0?}}, 0x0)
	/Users/oreilly/go/src/github.com/goki/gi/gi/layout.go:1205 +0x1a0
github.com/goki/gi/gi.(*Node2DBase).Layout2DChildren(0x14000ada000, 0x1400036c000?)
	/Users/oreilly/go/src/github.com/goki/gi/gi/node2d.go:875 +0xf8
github.com/goki/gi/gi.(*SplitView).Layout2D(0x14000ada000, {{0x14000ada000?, 0x101b5ac58?}, {0x140002bcc00?, 0x1400a6bb558?}}, 0x0?)
	/Users/oreilly/go/src/github.com/goki/gi/gi/splitview.go:400 +0x394
github.com/goki/gi/gi.(*Layout).Layout2DChildren(0x14000ad6000, 0x0?)
	/Users/oreilly/go/src/github.com/goki/gi/gi/layout.go:525 +0x1a4
github.com/goki/gi/gi.(*Layout).Layout2D(0x14000ad6000, {{0x14000ad6000?, 0x140002cabc0?}, {0x1400a6bb610?, 0x1400a6bb668?}}, 0x0)
	/Users/oreilly/go/src/github.com/goki/gi/gi/layout.go:1205 +0x1a0
github.com/goki/gi/gi.(*Layout).Layout2DChildren(0x140002bcc00, 0x0?)
	/Users/oreilly/go/src/github.com/goki/gi/gi/layout.go:525 +0x1a4
github.com/goki/gi/gi.(*Layout).Layout2D(0x140002bcc00, {{0x140002bcc00?, 0x0?}, {0x0?, 0x0?}}, 0x0)
	/Users/oreilly/go/src/github.com/goki/gi/gi/layout.go:1205 +0x1a0
github.com/goki/gi/gi.(*Node2DBase).Layout2DChildren(0x140002caa80, 0x101b3e028?)
	/Users/oreilly/go/src/github.com/goki/gi/gi/node2d.go:875 +0xf8
github.com/goki/gi/gi.(*Viewport2D).Layout2D(0x140002caa80, {{0x14000ba8000?, 0x0?}, {0x1018592d6?, 0x0?}}, 0x0?)
	/Users/oreilly/go/src/github.com/goki/gi/gi/viewport.go:482 +0x40
github.com/goki/gi/gi.(*Node2DBase).Layout2DTree(0x140002caa80)
	/Users/oreilly/go/src/github.com/goki/gi/gi/node2d.go:835 +0x190
github.com/goki/gi/gi.(*Node2DBase).FullRender2DTree(0x140002caa80)
	/Users/oreilly/go/src/github.com/goki/gi/gi/node2d.go:723 +0x50
github.com/goki/gi/gi.(*Viewport2D).FullRender2DTree(0x140002caa80?)
	/Users/oreilly/go/src/github.com/goki/gi/gi/viewport.go:577 +0x138
github.com/goki/gi/gi.(*Viewport2D).UpdateNodes(0x140002caa80)
	/Users/oreilly/go/src/github.com/goki/gi/gi/viewport.go:851 +0x6c0
github.com/goki/gi/gi.(*Viewport2D).SetNeedsFullRender(0x140002caa80?)
	/Users/oreilly/go/src/github.com/goki/gi/gi/viewport.go:811 +0xe8
github.com/emer/emergent/egui.(*GUI).UpdateWindow(...)
	/Users/oreilly/go/src/github.com/emer/emergent/egui/gui.go:39
main.(*Sim).ConfigGui.func1()
	/Users/oreilly/go/src/github.com/emer/axon/examples/ra25/ra25.go:505 +0x34
github.com/emer/emergent/egui.(*GUI).AddToolbarItem.func2({0x14005ac3250?, 0x101b3e028?}, {0x14000ba8000?, 0x1400a6bba80?}, 0x1400a6bbb48?, {0x100d8eaec?, 0x1400a6bbb28?})
	/Users/oreilly/go/src/github.com/emer/emergent/egui/toolbar.go:28 +0x28
github.com/goki/ki/ki.(*Signal).Emit(0x14005ac3250, {0x101b383b8, 0x14005ac1980}, 0x1400a6bbd40?, {0x0, 0x0})
	/Users/oreilly/go/src/github.com/goki/ki/ki/signal.go:173 +0x1e0
github.com/goki/gi/gi.(*Action).ButtonRelease(0x14005ac1980)
	/Users/oreilly/go/src/github.com/goki/gi/gi/action.go:223 +0xfc
github.com/goki/gi/gi.(*ButtonBase).MouseEvent.func1({0x101b383b8?, 0x14005ac1980}, {0x18?, 0x101a02f40?}, 0x1?, {0x101a42fa0?, 0x1400b508740})
	/Users/oreilly/go/src/github.com/goki/gi/gi/buttons.go:465 +0xc8
github.com/goki/gi/gi.(*WinEventRecv).Call(0x1400b508740?, {0x101b3e028?, 0x14000ba8000?}, 0x100df00e4?, {0x101a42fa0?, 0x1400b508740?})
	/Users/oreilly/go/src/github.com/goki/gi/gi/events.go:116 +0x10c
github.com/goki/gi/gi.(*EventMgr).SendEventSignal(0x14000ba8188, {0x101b2b950, 0x1400b508740}, 0x1)
	/Users/oreilly/go/src/github.com/goki/gi/gi/events.go:225 +0x640
github.com/goki/gi/gi.(*Window).ProcessEvent(0x14000ba8000, {0x101b2b950, 0x1400b508740})
	/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:1624 +0x5c4
github.com/goki/gi/gi.(*Window).EventLoop(0x14000ba8000)
	/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:1546 +0x34
github.com/goki/gi/gi.(*Window).StartEventLoop(0x102f42a00?)
	/Users/oreilly/go/src/github.com/goki/gi/gi/window.go:897 +0xb8
main.guirun()
	/Users/oreilly/go/src/github.com/emer/axon/examples/ra25/ra25.go:55 +0x38
main.main.func1()
	/Users/oreilly/go/src/github.com/emer/axon/examples/ra25/ra25.go:47 +0x20
github.com/goki/gi/gimain.Main.func1({0x0?, 0x0?})
	/Users/oreilly/go/src/github.com/goki/gi/gimain/gimain.go:32 +0x28
github.com/goki/gi/oswin/driver/vkos.Main.func1()
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/vkos/app.go:76 +0x44
created by github.com/goki/gi/oswin/driver/vkos.Main
	/Users/oreilly/go/src/github.com/goki/gi/oswin/driver/vkos/app.go:75 +0xb4

/Users/oreilly/go/src/github.com/emer/axon/examples/ra25/ra25 <b>failed</b> at: Mon Jun  13 15:45:52 PDT 2022 with error: exit status 2

**Comment by rcoreilly** [comment]
fixed with new test in GenPlot
